name: Release

on:
  workflow_call:
    inputs:
      runs_on:
        type: string
        default: 'ubuntu-latest'
      node_version:
        type: string
        default: '20.x'

permissions:
  contents: write
  id-token: write
  issues: read
  pull-requests: read

jobs:
  semantic-release:
    name: release
    runs-on: ${{ inputs.runs_on }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node_version }}
      - run: npm ci
      - run: npm install -g semantic-release @semantic-release/git @semantic-release/changelog -D
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
